- Github: Bus/Network/Handle_Bus_Network.ipynb

# 1 Creat Shapefile

- Read Data

    - `bus_routes_*.csv`

    - `bus_stops_*.csv`

    - `BusStopLocation.zip`: Extract CRS

In [ ]:
! pip install geopandas

In [6]:
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import LineString, Point

## 1.1 Read data

In [6]:
route_df_path = 'bus_routes_2022-06-19.csv'
route_df = pd.read_csv(route_df_path, header=0, index_col=None,
                       dtype = {'ServiceNo'    : str,
                                'Operator'     : str,
                                'StopSequence' : np.int16,
                                'Direction'    : np.int8,
                                'BusStopCode'  : str }
                       )

stop_df_path = 'bus_stops_2022-06-19.csv'
stop_df = pd.read_csv(stop_df_path,
                      dtype = {'BusStopCode' : str})

# CRS
path = "zip://BusStopLocation.zip!BusStopLocation_Jun2022/BusStop.shp"
CRS = gpd.read_file(path).crs

In [7]:
route_df = route_df.merge(right = stop_df, how = 'left',
                          on = 'BusStopCode')

# check if there exists some stops without location information 
stop_nan = route_df[route_df['Latitude'].isna()]['BusStopCode']
print(stop_nan)

Series([], Name: BusStopCode, dtype: object)

## 1.2 Create Line Segment Shapefile

In [8]:
line_seg_gpd = pd.DataFrame(columns = ['start_stop', 'end_stop', 
                                       'service_no', 'operator', 'direction',
                                       'distance', 'geometry'])

for name, group in route_df.groupby(by = ['Operator', 'ServiceNo', 'Direction']):
    operator, service_no, direction = name
    
    # some stop may be repeated
    group.drop_duplicates(inplace=True)
    group.sort_values(by='StopSequence', ignore_index=True, inplace=True)
    
    for ix in range(group.shape[0] - 1):
        
        start_stop     = group.loc[ix, 'BusStopCode']
        start_stop_lat = group.loc[ix, 'Latitude']
        start_stop_lng = group.loc[ix, 'Longitude']
        start_stop_geo = Point(start_stop_lng, start_stop_lat)
        
        end_stop     = group.loc[ix+1, 'BusStopCode']
        end_stop_lat = group.loc[ix+1, 'Latitude']
        end_stop_lng = group.loc[ix+1, 'Longitude']
        end_stop_geo = Point(end_stop_lng, end_stop_lat)
        
        line_geo = LineString([start_stop_geo, end_stop_geo])
        line_dist = group.loc[ix+1, 'Distance'] - group.loc[ix, 'Distance']
        
        try:
            assert line_dist > 0.
        except:
            print(name, line_dist)
            # sys.exit(0)
            
        one_row = pd.Series({'start_stop' : start_stop,
                             'end_stop'   : end_stop, 
                             'service_no' : service_no, 
                             'operator'   : operator, 
                             'direction'  : direction, 
                             'distance'   : line_dist,        
                             'geometry'   : line_geo.wkt})
        one_row = one_row.to_frame().transpose()
        
        line_seg_gpd = pd.concat([line_seg_gpd, one_row], axis=0, ignore_index=True)

line_seg_gpd = gpd.GeoDataFrame(line_seg_gpd, 
                                geometry = gpd.GeoSeries.from_wkt(line_seg_gpd['geometry']),
                                crs = 'EPSG:4326')     

# modify the data type of 'direction' column
line_seg_gpd = line_seg_gpd.astype({'direction': np.int8})


line_seg_gpd

('GAS', '68', 1) 0.0
('SBST', '160', 1) 0.0
('SBST', '160', 1) 0.0
('SBST', '160', 1) 0.0
('SBST', '160', 1) 0.0
('SBST', '265', 1) 0.0
('SBST', '265', 1) 0.0
('SBST', '48', 1) 0.0
('SBST', '48', 2) 0.0
('SBST', '69', 1) 0.0
('SBST', '812', 1) 0.0
('SBST', '812T', 1) 0.0
('SBST', '860', 1) 0.0
('SBST', '89A', 1) 0.0
('SBST', '9', 1) 0.0
('SBST', '9', 1) 0.0
('SBST', 'CT8', 1) 0.0
('SMRT', '950', 1) 0.0
('SMRT', '950', 1) 0.0
('SMRT', '950', 1) 0.0
('SMRT', '950', 1) 0.0

,start_stop,end_stop,service_no,operator,direction,distance,geometry
0,65009,65259,118,GAS,1,0.4,"LINESTRING (103.90224 1.40371, 103.90187 1.40535)"
1,65259,65409,118,GAS,1,0.3,"LINESTRING (103.90187 1.40535, 103.89957 1.40624)"
2,65409,65141,118,GAS,1,0.4,"LINESTRING (103.89957 1.40624, 103.89716 1.40455)"
3,65141,65431,118,GAS,1,0.2,"LINESTRING (103.89716 1.40455, 103.89674 1.40239)"
4,65431,65199,118,GAS,1,1.3,"LINESTRING (103.89674 1.40239, 103.90543 1.39592)"
...,...,...,...,...,...,...,...
25294,58151,58111,NR2,TTS,1,0.3,"LINESTRING (103.82201 1.44836, 103.82075 1.45096)"
25295,58111,58421,NR2,TTS,1,0.3,"LINESTRING (103.82075 1.45096, 103.81903 1.45131)"
25296,58421,58311,NR2,TTS,1,0.2,"LINESTRING (103.81903 1.45131, 103.81810 1.45020)"
25297,58311,58251,NR2,TTS,1,0.3,"LINESTRING (103.81810 1.45020, 103.81895 1.44803)"
25298,58251,58291,NR2,TTS,1,0.3,"LINESTRING (103.81895 1.44803, 103.81994 1.44579)"

## 1.3 Create Line and Stop Shapefile

In [9]:
line_route_gpd = line_seg_gpd.copy()[['service_no', 'operator', 'direction', 'distance', 'geometry']]
line_route_gpd = line_route_gpd.dissolve(
    by = ['service_no', 'operator', 'direction'], 
    aggfunc ='sum',
    as_index = False)

line_route_gpd

,service_no,operator,direction,geometry,distance
0,10,SBST,1,"MULTILINESTRING ((103.94339 1.35408, 103.94165...",31.6
1,10,SBST,2,"MULTILINESTRING ((103.76988 1.29425, 103.76908...",31.9
2,100,SBST,1,"MULTILINESTRING ((103.87169 1.35047, 103.87205...",23.6
3,100,SBST,2,"MULTILINESTRING ((103.78932 1.31107, 103.78969...",23.3
4,100A,SBST,1,"MULTILINESTRING ((103.87169 1.35047, 103.87205...",4.8
...,...,...,...,...,...
714,NR2,TTS,1,"MULTILINESTRING ((103.86149 1.29147, 103.86183...",36.6
715,NR3,SMRT,1,"MULTILINESTRING ((103.84820 1.28712, 103.84924...",30.8
716,NR5,SMRT,1,"MULTILINESTRING ((103.86149 1.29147, 103.86183...",33.7
717,NR6,SMRT,1,"MULTILINESTRING ((103.82570 1.25352, 103.82211...",36.4
718,NR8,SMRT,1,"MULTILINESTRING ((103.86149 1.29147, 103.86183...",24.4

In [10]:
start_stop_gpd = line_seg_gpd['start_stop'].drop_duplicates()
end_stop_gpd = line_seg_gpd['end_stop'].drop_duplicates()
stop_gpd = pd.concat([start_stop_gpd, end_stop_gpd], axis=0, ignore_index=True).drop_duplicates()

stop_gpd = stop_gpd.to_frame(name = 'BusStopCode')
stop_gpd = stop_gpd.merge(right = stop_df, how = 'left',
                          on = 'BusStopCode')

stop_gpd = gpd.GeoDataFrame(stop_gpd[['BusStopCode', 'RoadName', 'Description']], 
                            geometry = gpd.geopandas.points_from_xy(stop_gpd['Longitude'], stop_gpd['Latitude']),
                            crs = 'EPSG:4326')

stop_gpd

,BusStopCode,RoadName,Description,geometry
0,65009,Punggol Pl,Punggol Temp Int,POINT (103.90224 1.40371)
1,65259,Punggol Ctrl,Punggol Stn/Int,POINT (103.90187 1.40535)
2,65409,Punggol Ctrl,Bef Blk 264,POINT (103.89957 1.40624)
3,65141,Punggol Way,Aft Soo Teck Stn,POINT (103.89716 1.40455)
4,65431,Punggol Way,Twin Waterfalls,POINT (103.89674 1.40239)
...,...,...,...,...
5077,47179,Senoko Loop,Comfortdelgro Engrg,POINT (103.79881 1.45828)
5078,47189,Senoko Loop,K.U.S. Holdings,POINT (103.80129 1.45900)
5079,47199,Senoko Loop,Bef Senoko Dr,POINT (103.80266 1.46124)
5080,28201,Jurong Gateway Rd,Opp The JTC Summit,POINT (103.74185 1.33206)
5081,59599,Yishun Ave 6,Opp Blk 406,POINT (103.84968 1.42641)

## 1.4 Change CRS and Save file

In [ ]:
line_seg_gpd = line_seg_gpd.to_crs(CRS)
line_route_gpd = line_route_gpd.to_crs(CRS)
stop_gpd = stop_gpd.to_crs(CRS)

line_seg_gpd.to_file('Bus Network Shapefile/bus_line_segment/bus_line_segment.shp')
line_route_gpd.to_file('Bus Network Shapefile/bus_line/bus_line.shp')
stop_gpd.to_file('Bus Network Shapefile/bus_stop/bus_stop.shp')

# 2. Creat bus line topology Shapefile

- data is collected from the github project: [site]()

    - `routes.min.geojson` file

In [10]:
# reference CRS
file_path = 'zip://Bus Network Shapefile/Bus Network Shapefile.zip!Bus Network Shapefile/bus_line/bus_line.shp'
CRS = gpd.read_file(file_path).crs
CRS

<Projected CRS: PROJCS["SVY21",GEOGCS["WGS 84",DATUM["WGS_1984",SP ...>
Name: SVY21
Axis Info [cartesian]:
- [east]: Easting (metre)
- [north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Transverse Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [12]:
file_path = 'https://raw.githubusercontent.com/cheeaun/sgbusdata/main/data/v1/routes.min.geojson'
line_gpd = gpd.read_file(file_path)

line_gpd = line_gpd.to_crs(CRS)
line_gpd

line_gpd.to_file('bus_line_topology.shp')